import "../styles/globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import type { AppProps } from "next/app";
import SSRProvider from "react-bootstrap/SSRProvider";

import Head from "next/head";
import { Header } from "../components/header";
import { SessionProvider } from "next-auth/react";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <SSRProvider>
      <Head>
        <title>TBG-Admin</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SessionProvider>
        <Header></Header>
        <main>
          <Component {...pageProps} />
        </main>
      </SessionProvider>

      <footer></footer>
    </SSRProvider>
  );
}

export default MyApp;
